### ISSUE TITLE
alarmdotcom doesn't load after reboot

### ISSUE THREAD

**Issue by lubo1953** [uvjustin/alarmdotcom#119]
I'm having a problem with alarmdotcom reloading after I reboot. Once HA is rebooted, I'm able to disable alarmdocom and then enable it and it loads. Everything work fine afterwards, but it the inconvenience of having to restart it as I have my security camera programmed to start or stop based on the alarm settings. Error's I'm receiving are below.

![image](https://user-images.githubusercontent.com/80802946/164053231-b7c30c58-1b47-42ca-b5a0-36c6a87fa7f9.png)

**Comment by elahd** [comment]
@lubo1953 Would you be able to click on the error messages to share the technical details?

**Comment by lubo1953** [comment]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/controller.py:89
Integration: Alarm.com (documentation, issues)
First occurred: 7:59:27 PM (1 occurrences)
Last logged: 7:59:27 PM

Error setting up entry Central ***@***.*** for alarmdotcom
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 880, in _async_login_and_get_key
    async with self._websession.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.alarm.com:443 ssl:default [Connection reset by peer]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/controller.py", line 87, in async_login
    login_result = await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 178, in async_login
    await self._async_login_and_get_key()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 912, in _async_login_and_get_key
    await asyncio.sleep(60)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 656, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 48, in async_setup_entry
    if not await controller.async_setup():
  File "/config/custom_components/alarmdotcom/controller.py", line 131, in async_setup
    await self.async_login(
  File "/config/custom_components/alarmdotcom/controller.py", line 89, in async_login
    return login_result
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

This error originated from a custom integration.

Logger: custom_components.alarmdotcom.controller
Source: custom_components/alarmdotcom/controller.py:101
Integration: Alarm.com (documentation, issues)
First occurred: 7:59:27 PM (1 occurrences)
Last logged: 7:59:27 PM

custom_components.alarmdotcom.controller: Error logging in:


Logger: pyalarmdotcomajax
Source: /usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py:908
First occurred: 7:59:04 PM (1 occurrences)
Last logged: 7:59:04 PM

Can not load login page from Alarm.com


Cheers,
Lou

When the end grows near, I don’t want to be the one who looks back on his life with regrets for the things I wish I had done.
I want to be the one who can look back on my life and reflect on the memories of things I’ve done, the things I’ve accomplished and the places I’ve traveled.
One thing is certain about life; it is not so much the destination as it is the journey.

**Comment by elahd** [comment]
Can you update to v0.2.7-beta and see if you still run into this issue?

**Comment by elahd** [comment]
@lubo1953 Can you update to v0.2.7-beta and see if you still run into this issue?

**Comment by lubo1953** [comment]
That seems to have fixed it. I’ve restarted HA several times and it’s loaded every time. Thank you for the help.

Cheers,
Lou

When the end grows near, I don’t want to be the one who looks back on his life with regrets for the things I wish I had done.
I want to be the one who can look back on my life and reflect on the memories of things I’ve done, the things I’ve accomplished and the places I’ve traveled.
One thing is certain about life; it is not so much the destination as it is the journey.
