### ISSUE TITLE
Not working after latest core update.

### ISSUE THREAD

**Issue by bkr1969** [uvjustin/alarmdotcom#123]
Logger: pyalarmdotcomajax
Source: /usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py:955
First occurred: 08:40:59 (1 occurrences)
Last logged: 08:40:59

Unable to extract ajax key from Alarm.com. Response: <ClientResponse(https://www.alarm.com/web/DetermineLandingPage.aspx) [503 Service Unavailable]> <CIMultiDictProxy('Content-Type': 'text/html', 'Server': 'Microsoft-IIS/10.0', 'P3P': 'policyref="/w3c/p3p.xml",CP="OUR SAMa ADM UNI BUS ALL CUR DSP TAI COR IND STA"', 'Access-Control-Allow-Origin': '*', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-UA-Compatible': 'IE=edge', 'Date': 'Mon, 25 Apr 2022 14:40:58 GMT', 'Content-Length': '27')>

**Comment by bkr1969** [comment]
2022-04-25 08:45:18 ERROR (MainThread) [custom_components.alarmdotcom.controller] custom_components.alarmdotcom.controller: Error logging in: 
2022-04-25 08:45:18 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Brinks Home™:[my_accout_email] for alarmdotcom
Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/controller.py", line 87, in async_login
    login_result = await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 178, in async_login
    await self._async_login_and_get_key()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 921, in _async_login_and_get_key
    async with self._websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 48, in async_setup_entry
    if not await controller.async_setup():
  File "/config/custom_components/alarmdotcom/controller.py", line 131, in async_setup
    await self.async_login(
  File "/config/custom_components/alarmdotcom/controller.py", line 89, in async_login
    return login_result
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by bkr1969** [comment]
This error originated from a custom integration.

Logger: custom_components.alarmdotcom.controller
Source: custom_components/alarmdotcom/controller.py:101
Integration: Alarm.com (documentation, issues)
First occurred: 08:53:39 (1 occurrences)
Last logged: 08:53:39

custom_components.alarmdotcom.controller: Error logging in:

**Comment by elahd** [comment]
Looks like a timeout that occurred because of slowness on boot. v0.2.7-beta.2 attempts to address this. Would you mind upgrading to see if this fixes the problem?

**Comment by BradTX77** [comment]
@elahd The beta update resolved the issue for me. Thank you!
