### ISSUE TITLE
Alarm dot com broken out of nowhere

### ISSUE THREAD

**Issue by bkr1969** [uvjustin/alarmdotcom#44]
From my core logs:
`
2021-08-06 09:47:20 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract system id from Alarm.com
2021-08-06 09:47:20 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 96, in async_setup_platform
    await alarmdotcom.async_login()
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 156, in async_login
    await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 206, in async_login
    return await self._async_get_system_info()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 166, in _async_get_system_info
    self._systemid = json["data"][0]["id"]
KeyError: 'data'
`

**Comment by cecilkootz** [comment]
I have the same issue. When looking at the `pyalarmdotcomajax` source and trying a few options it appears the login works as I get a 200 response but when fetching `availableSystemItems` I get `403 Forbidden`. Perhaps Alarm.com has started blocking these requests?

**Comment by tcm0116** [comment]
I'm having a similar issues. Here's my log:
```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/alarmdotcom/alarm_control_panel.py:160
Integration: alarmdotcom (documentation)
First occurred: August 3, 2021, 3:35:28 PM (2715 occurrences)
Last logged: 10:29:34 PM

Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 222, in async_update
    self.sensor_status = json["data"]["attributes"]["needsClearIssuesPrompt"]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 617, in async_device_update
    await task
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 242, in async_update
    await self.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 212, in async_update
    await self.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 206, in async_login
    return await self._async_get_system_info()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 166, in _async_get_system_info
    self._systemid = json["data"][0]["id"]
KeyError: 'data'
```

**Comment by bkr1969** [comment]
OK...Just as suddenly as it stopped working last week, it's back up again now.

**Comment by tcm0116** [comment]
It is working for me again, as well.

**Comment by cecilkootz** [comment]
I am still getting the error. Removed, reset, added, 2fa, etc and no luck

**Comment by uvjustin** [comment]
Sorry, no idea what happened, but glad it got resolved.
