### ISSUE TITLE
Unable to extract ajax key

### ISSUE THREAD

**Issue by millerjryan** [uvjustin/alarmdotcom#46]
```
2021-09-24 13:21:52 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract ajax key from Alarm.com
2021-09-24 13:21:53 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alarmdotcom platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 96, in async_setup_platform
    await alarmdotcom.async_login()
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 156, in async_login
    await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 204, in async_login
    if not await self._async_get_ajax_key():
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 150, in _async_get_ajax_key
    self._ajax_headers["ajaxrequestuniquekey"] = resp.cookies["afg"].value
KeyError: 'afg'
```

I am facing the above error today.  I can't seem to figure out why is can't extract the ajax key.  This was working last night.

**Comment by millerjryan** [comment]
I am blind, and my password was off.
