### ISSUE TITLE
Alarmdotcom .. state = unknown

### ISSUE THREAD

**Issue by HazardousRat** [uvjustin/alarmdotcom#60]
I'm running core-2021.12.1 .. It appeared to be working fine after the recent 12.0 update, not sure if 12.1 caused the issue.  I have restarted and no change, still indicates state status is unknown.  Can someone please look into this and fix?

**Comment by maniscalcojohn** [comment]
I’m also seeing lots of errors this morning. The state is incorrect. 

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:260 
First occurred: 6:09:59 AM (213 occurrences) 
Last logged: 7:53:59 AM

Unable to extract sensor status from Alarm.com

**Comment by acockburn** [comment]
This is happening to me too as of this morning, HASS is reporting:

Logger: pyalarmdotcomajax.pyalarmdotcomajax
Source: /Users/acockburn/venv/hass/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py:260 
First occurred: 8:48:36 AM (8 occurrences) 
Last logged: 8:52:06 AM

Unable to extract sensor status from Alarm.com

and 

Logger: homeassistant.helpers.entity
Source: custom_components/alarmdotcom/alarm_control_panel.py:160 
Integration: alarmdotcom (documentation, issues) 
First occurred: 8:48:36 AM (8 occurrences) 
Last logged: 8:52:06 AM

Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/Users/acockburn/venv/hass/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/Users/acockburn/venv/hass/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/Users/acockburn/hass/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/Users/acockburn/venv/hass/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'

I haven't changed any software, and was already set up for 2FA. To be sure, I logged back into the site and verified the 2FA token which hadn't changed.

**Comment by bkr1969** [comment]
Same.  Unable to arm or disarm by automation.
``
KeyError: 'stateText'
2021-12-13 07:59:37 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract sensor status from Alarm.com
2021-12-13 07:59:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'
2021-12-13 08:00:03 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract sensor status from Alarm.com
2021-12-13 08:00:03 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall alarm_control_panel.alarm_arm_home (c:6519bc32fb4b7c7c5c1c0cb1b545c89d): entity_id=['alarm_control_panel.alarm_com'], code=>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 208, in async_alarm_arm_home
    await self._alarm.async_alarm_arm_stay()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 392, in async_alarm_arm_stay
    await self._send("Arm+Stay", forcebypass, noentrydelay, silentarming)
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 360, in _send
    await self.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'
2021-12-13 08:00:06 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract sensor status from Alarm.com
2021-12-13 08:00:06 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'
2021-12-13 08:00:37 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract sensor status from Alarm.com
2021-12-13 08:00:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'
2021-12-13 08:00:44 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract sensor status from Alarm.com
2021-12-13 08:00:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473224947504] 'stateText'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 203, in async_alarm_disarm
    await self._alarm.async_alarm_disarm()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 385, in async_alarm_disarm
    await self._send("Disarm", False, False, False)
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 360, in _send
    await self.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'
2021-12-13 08:01:07 ERROR (MainThread) [pyalarmdotcomajax.pyalarmdotcomajax] Unable to extract sensor status from Alarm.com
2021-12-13 08:01:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 254, in async_update
    + sensor["attributes"]["stateText"]
KeyError: 'stateText'
``

**Comment by mikesalz** [comment]
Same here :(

**Comment by mikesalz** [comment]
I agree with @bkr1969.  My issues started this morning while I was still on 2021.11.5.  I upgraded to 2021.12.1 today and am still experiencing the problem.

**Comment by davidbrenner1** [comment]
Same issue...had the problem on both 2021.12 and 2021.12.1.

Logger: homeassistant.helpers.entity
Source: custom_components/alarmdotcom/alarm_control_panel.py:160
Integration: alarmdotcom (documentation, issues)
First occurred: 9:33:00 AM (30 occurrences)
Last logged: 9:47:30 AM

Update for alarm_control_panel.alarm_com fails

**Comment by uvjustin** [comment]
I see it too. Let me try to push a fix

**Comment by uvjustin** [comment]
Pushed a new version, try it.
I don't use hacs so not sure if it's updated there. I can check that later

**Comment by davidbrenner1** [comment]
I forced a re-download and HACS and restarted and that fixed it.  Thanks for the quick turnaround @uvjustin.  Really appreciate it.

**Comment by acockburn** [comment]
Sounds promising - I'll give it a try this evening and report back.

**Comment by bkr1969** [comment]
Also updated via HACS and it's working now.  Thanks!

**Comment by acockburn** [comment]
Yes, all is well here too - thanks for the super-fast turnaround @uvjustin, much appreciated!

**Comment by uvjustin** [comment]
Great, glad it worked!
