### ISSUE TITLE
Alarm.Com with Readonly User with limited access

### ISSUE THREAD

**Issue by robin-vandaele** [uvjustin/alarmdotcom#77]
Hi
Could it be possible to enable alarm.com with a user that has no access to the security codes and read-only access to the other parts. That way we can create an API only user with limited access.
Now the integration breaks when we disable code access.

**Comment by elahd** [comment]
This works for me using a read only account on v0.2.0-beta.5. Which version of the integration are you using? Are you able to share more detailed logs?

**Comment by robin-vandaele** [comment]
I'm using the latest version.
When I'm using a user who has not "Full" readonly access, but "readonly access to everything but the panel user codes" it doesn't work.

Logger: aiohttp.server
Source: custom_components/alarmdotcom/controller.py:409
Integration: Alarm.com (documentation, issues)
First occurred: 28 januari 2022 22:02:04 (2 occurrences)
Last logged: 28 januari 2022 22:05:59

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alarmdotcom/config_flow.py", line 57, in async_step_user
    api = await get_controller(
  File "/config/custom_components/alarmdotcom/controller.py", line 409, in get_controller
    await controller.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 151, in async_login
    await self.async_update()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 209, in async_update
    await self._async_get_partitions()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 273, in _async_get_partitions
    entities = await self._async_get_items_and_subordinates(
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 569, in _async_get_items_and_subordinates
    raise DeviceTypeNotAuthorized
pyalarmdotcomajax.errors.DeviceTypeNotAuthorized

**Comment by elahd** [comment]
Thanks. This should be fixed in beta 7. Can you try updating and report back?

**Comment by robin-vandaele** [comment]
I can confirm I can prohibit access to the panel codes & put everything in Read Only.
Thanks for the supprt.
