### ISSUE TITLE
Error Setting up Integration after Restart

### ISSUE THREAD

**Issue by sercanerhan** [uvjustin/alarmdotcom#98]
# Problem

Alarmdotcom integration works perfectly until I restart the Home Assistant. After the restart, looks like the Integration lose the login information.

## Expectation
Alarmdotcom integration should work smoothly and be able to re-connect to the alarmdotcom even I restart my Home Assistant.

# Versions and Env
**Home Assistant Os version**: 2022.3.6
**Alarmdotcom integration HACS repo version**: 0.2.1
Hardware: RPi 3

# Steps
* Install HASC repo for alarmdotcom
* install Integration for alarmdotcom
* setup alarmdotcom information by providing credentials
* get successful messages
* see, validate the sensor and assign them to zones
* everything looks like running smoothly
*  restart the Home Assistant
* Lose the alarmdotcom integration
* access below logs

The above steps are reproducible. If I re-enter my credentials and re-complete the setup, everything will be working until I restart the Home Assistant.

# Integration Error Logs
```python
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmdotcom/controller.py:109
Integration: Alarm.com (documentation, issues)
First occurred: March 23, 2022, 11:48:10 AM (1 occurrences)
Last logged: March 23, 2022, 11:48:10 AM

Error setting up entry Pronet Güvenlik Hizmetleri:YOUREMAILADDRESS for alarmdotcom
Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/controller.py", line 107, in async_login
    login_result = await self._alarm.async_login()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 188, in async_login
    await self._async_login_and_get_key()
  File "/usr/local/lib/python3.9/site-packages/pyalarmdotcomajax/__init__.py", line 943, in _async_login_and_get_key
    async with self._websession.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmdotcom/__init__.py", line 39, in async_setup_entry
    if not await controller.async_setup():
  File "/config/custom_components/alarmdotcom/controller.py", line 141, in async_setup
    await self.async_login(
  File "/config/custom_components/alarmdotcom/controller.py", line 109, in async_login
    return login_result
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

```

**Comment by elahd** [comment]
@sercanerhan Would you mind testing v0.2.2-beta?

**Comment by sercanerhan** [comment]
Hi @elahd after several core restarts, I couldn't get any issue. It works smoothly, thank you 🎉

**Comment by elahd** [comment]
Awesome! Credit goes to @AritroSaha10 for the fix.

**Comment by sercanerhan** [comment]
Thank you @AritroSaha10 🎉
